apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: syednaqiabbas/agribuddy-backend:latest

          ports:
            - containerPort: 8000

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

            requests:
              memory: "256Mi"
              cpu: "250m"